### ISSUE TITLE
Es posible quitar los meses en el eje x dentro de las gráficas de lineas

### ISSUE THREAD

**Issue by luiscolungaperez** [salsa-community/dadsig-graficas#41]
Me gustaría saber sí es posible dejar de visualizar los meses dentro de las gráficas de lineas cuando solo se maneja por año.

Pasar de "ene/2022" -> "2022"

**Comment by jdanielgoh** [comment]
Hooola Luis! no lo hemos considerado en el componente porque las etiquetas se ponen de forma automática con d3 mediante la escala temporal. Voy a revisar como podríamos conseguir eso :)
